/********************************************************************
 * ADOBE CONFIDENTIAL
 * __________________
 *
 *  Copyright 2024 Adobe
 *  All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 *******************************************************************/
export declare const setBillingAddressOnCartMutation = "\n  mutation setBillingAddress(\n    $cartId: String!\n    $billingAddress: BillingAddressInput!\n  ) {\n    setBillingAddressOnCart(\n      input: { cart_id: $cartId, billing_address: $billingAddress }\n    ) {\n      cart {\n        ...CHECKOUT_DATA_FRAGMENT\n      }\n    }\n  }\n\n  \n  fragment CHECKOUT_DATA_FRAGMENT on Cart {\n    id\n    is_virtual\n    email\n    total_quantity\n    billing_address {\n      ...BILLING_CART_ADDRESS_FRAGMENT\n    }\n    shipping_addresses {\n      ...SHIPPING_CART_ADDRESS_FRAGMENT\n    }\n    available_payment_methods {\n      ...AVAILABLE_PAYMENT_METHOD_FRAGMENT\n    }\n    selected_payment_method {\n      ...SELECTED_PAYMENT_METHOD_FRAGMENT\n    }\n  }\n\n  \n  fragment BILLING_CART_ADDRESS_FRAGMENT on BillingCartAddress {\n    city\n    company\n    country {\n      code\n      label\n    }\n    custom_attributes {\n      ... on AttributeValue {\n        code\n        value\n      }\n    }\n    fax\n    firstname\n    id\n    lastname\n    middlename\n    postcode\n    prefix\n    region {\n      region_id\n      code\n      label\n    }\n    street\n    suffix\n    telephone\n    uid\n    vat_id\n  }\n\n  \n  fragment SHIPPING_CART_ADDRESS_FRAGMENT on ShippingCartAddress {\n    available_shipping_methods {\n      ...AVAILABLE_SHIPPING_METHOD_FRAGMENT\n    }\n    city\n    company\n    country {\n      code\n      label\n    }\n    custom_attributes {\n      ... on AttributeValue {\n        code\n        value\n      }\n    }\n    fax\n    firstname\n    id\n    lastname\n    middlename\n    postcode\n    prefix\n    region {\n      region_id\n      code\n      label\n    }\n    same_as_billing\n    selected_shipping_method {\n      ...SELECTED_SHIPPING_METHOD_FRAGMENT\n    }\n    street\n    suffix\n    telephone\n    uid\n    vat_id\n  }\n\n  \n  fragment AVAILABLE_SHIPPING_METHOD_FRAGMENT on AvailableShippingMethod {\n    amount {\n      currency\n      value\n    }\n    carrier_code\n    carrier_title\n    error_message\n    method_code\n    method_title\n    price_excl_tax {\n      value\n      currency\n    }\n    price_incl_tax {\n      value\n      currency\n    }\n  }\n\n  \n  fragment SELECTED_SHIPPING_METHOD_FRAGMENT on SelectedShippingMethod {\n    amount {\n      currency\n      value\n    }\n    carrier_code\n    carrier_title\n    method_code\n    method_title\n    price_excl_tax {\n      value\n      currency\n    }\n    price_incl_tax {\n      value\n      currency\n    }\n  }\n\n\n  \n  fragment AVAILABLE_PAYMENT_METHOD_FRAGMENT on AvailablePaymentMethod {\n    code\n    title\n  }\n\n  \n  fragment SELECTED_PAYMENT_METHOD_FRAGMENT on SelectedPaymentMethod {\n    code\n    title\n    purchase_order_number\n  }\n\n\n";
