/********************************************************************
 * ADOBE CONFIDENTIAL
 * __________________
 *
 *  Copyright 2024 Adobe
 *  All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 *******************************************************************/
import { FetchQueryError } from '../api/fetch-graphql';
type ErrorPath = (string | number)[];
export type ErrorWithPath = FetchQueryError[number] & {
    path?: ErrorPath;
};
/**
 * Filters out errors with known paths from a list of errors generated by a GraphQL query.
 *
 * Known issue: The query does not differentiate between physical and virtual gift cards, leading
 * to errors for physical ones as they don't have 'sender_email' and 'recipient_email' properties.
 *
 * @param {ErrorWithPath[]} errors - Array of errors to be filtered.
 * @return {ErrorWithPath[]} Uncontrolled (unexpected) errors not matching predefined paths.
 */
export declare function filterControlledErrors(errors: ErrorWithPath[]): ErrorWithPath[];
export {};
